apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pramodhmdtpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pramodhmdtpipelinesjavascriptdocker 
    spec:
      containers:
        - name: pramodhmdtpipelinesjavascriptdocker 
          image: javacontainerregpramodh.azurecr.io/pramodhmdtpipelinesjavascriptdocker
          ports:
          - containerPort: 8080